'''
@author Ozer Ozdikis
@license:  See 'LICENSE.md' as part of this package.
@precondition:
@summary:
'''

'''
Paths to the training and test files, which must be provided to the application.  
Each line must include tab-separated fields of:
- grid cell id (Integer): The id of the grid cell that represents the posted location of tweet
- latitude (Float): latitude for the posted location of tweet 
- longitude (Float): longitude for the posted location of tweet
- tokens (String): tokens in tweet text separated by space
'''    
training_file = '/path/to/training_data'
test_file = '/path/to/test_data'

'''
Path to the grid definition file, which must be provided to the application. 
It represents the grid that divides the region into grid cells. Each line must include tab-separated fields of:
- grid cell id (Integer): A unique id for the grid cell.
- latmin (Float): latitude of the south-western corner of the grid cell 
- lonmin (Float): longitude of the south-western corner of the grid cell
- latmax (Float): latitude of the north-eastern corner of the grid cell
- lonmax (Float): longitude of the north-eastern corner of the grid cell
'''    
grid_file = '/path/to/grid_definition_file'

'''
This file will be generated by the application.
cooc.main_cooc.py writes the co-occurrence analysis results into this file, which is then used in classification.
'''
kscore_analysis_file = '/path/to/kscore_analysis_file'